### ISSUE TITLE
Save spells import incorrectly from the character sheet/monster block

### ISSUE THREAD

**Issue by MrPrimate** [VTTAssets/vtta-dndbeyond#11]
These are normally spells with saves. Some example spells I noticed importing from the Arcarnoloth monster: Chain Lightning and Finger of Death

If the spell is imported from the spell page it works.

If it is imported from the monster stat block or via the D&D Beyond character importer they don't always show up right:
- set as attack spells or other rather than saving throw spells.

**Comment by VTTAssets** [comment]
Note: Need to refactor the spell-tooltip/spell-page parser to use the same logic in order to avoid forgetting to transfer changes

**Comment by VTTAssets** [comment]
Refactored to use only one spell parsing engine when parsing D&D Beyond website data (again), so this should parse consistently. Still need to check/ work on the character import parser.
