### ISSUE TITLE
Tortle Monk import - AC & bonus actions

### ISSUE THREAD

**Issue by shawndibble** [VTTAssets/vtta-dndbeyond#125]
https://www.dndbeyond.com/profile/Heroworks/characters/25727501

When importing the above tortle account, AC comes in at 19 instead of 17. In addition, the bonus actions are not imported. Player can't bring in flurry of blows

**Comment by MrPrimate** [comment]
AC is fxed in next release.

**Comment by MrPrimate** [comment]
This is fixed with the latest release
