### ISSUE TITLE
currency being overwritten on import 

### ISSUE THREAD

**Issue by moadazzuz** [VTTAssets/vtta-dndbeyond#136]
See settings below.
![image](https://user-images.githubusercontent.com/29159283/81991467-dfe5b480-9673-11ea-919f-730552198274.png)

Currency is being overwritten despite "weapons", "equipment" and "Other inventory items" being deselected.

**Comment by VTTAssets** [comment]
Currency in dndbeyond and Foundry data terms is not an item, and therefore not in one of those categories. It is included in the base data update, which is run if you deselect every checkbox here.
