### ISSUE TITLE
warlock magic imported incorrectly

### ISSUE THREAD

**Issue by moadazzuz** [VTTAssets/vtta-dndbeyond#137]
![image](https://user-images.githubusercontent.com/29159283/81991647-5682b200-9674-11ea-840e-ba9751ba85ee.png)

![image](https://user-images.githubusercontent.com/29159283/81991868-cbee8280-9674-11ea-838f-2cf23fae61a6.png)

![image](https://user-images.githubusercontent.com/29159283/81991890-dad53500-9674-11ea-84a8-41f4028f10b3.png)

The 2nd level spells are imported as "Pact Magic" with spell slots.

**Comment by MrPrimate** [comment]
Warlock spells should be imported as Warlock Pact spells, as this is what they are. it should be adding your spell slots though. can you list the versions of module and software you are using, and upload a character json?

**Comment by moadazzuz** [comment]
Foundry version: 0.5.5
D&D 5th edition version: 0.87
vtta-dndbeyond version: 2.2.13

I've attached the JSON file. Thanks for looking into this.

[sample-warlock-json.txt](https://github.com/VTTAssets/vtta-dndbeyond/files/4634561/sample-warlock-json.txt)

**Comment by moadazzuz** [comment]
I should also mention that I can't modify the spell slots manually.

**Comment by MrPrimate** [comment]
I believe this is a bug with 0,87 of the D&D5e system, can you update to v0.8.8 please

**Comment by moadazzuz** [comment]
I updated to v0.8.8 and it appears to have fixed the problem thanks.
