### ISSUE TITLE
Reference to invalid shared module

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#151]
**Reported by:** Rune on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/684421955314909194/713864582812270592)
  

  
> The module settings for DDB Integration references a designated sharing module at the following URL - https://www.vttassets.com/asset/shared but this appears to lead to a "Not Found" on your website.

**Comment by mtvjr** [comment]
Screenshot 
![image](https://user-images.githubusercontent.com/9865643/82740965-3194db80-9d13-11ea-9156-d0053a78a470.png)

**Comment by VTTAssets** [comment]
Removed the hint regarding the shared module since vtta-dndbeyond now creates world-specific compendia on first run automatically and sets them as a default.
