### ISSUE TITLE
Styling impacts Config settings

### ISSUE THREAD

**Issue by shawndibble** [VTTAssets/vtta-dndbeyond#171]
It appears that VTTA-dndbeyond impacts with fvtt-uii_game-setting in that text gets centered in the Config settings when vtta-dndbeyond is enabled. Possibly some css rules are overflowing and impacting config settings.

https://raw.githubusercontent.com/sdenec/fvtt-uii_game-settings/master/module.json

![image](https://user-images.githubusercontent.com/1980293/83029365-3948ce80-9ff8-11ea-8302-abe5a9fe3afc.png)

**Comment by VTTAssets** [comment]
yes, those are alignment fixes for the default settings panel with the Filepicker buttons I do add for choosing directories and images. I will try to solve that
