### ISSUE TITLE
Icon on character sheet not fetched correctly on prefixed path

### ISSUE THREAD

**Issue by Dudrie** [VTTAssets/vtta-dndbeyond#174]
# Description
If foundry is served from a prefixed path (ie the global variable `ROUTE_PREFIX` is set on the client) the icon of this module on the character sheet is not loading properly. This is due to the following fetch made:

Expected route: `https://HOST/ROUTE_PREFIX/modules/vtta-dndbeyond/img/ddb-icon-inactive.png`

Actual route used by the module:  `https://HOST/modules/vtta-dndbeyond/img/ddb-icon-inactive.png` (note the missing "ROUTE_PREFIX" placeholder).

# Versions
- Foundry: 0.6.0
- VTTA dndbeyond: 2.2.15

**Comment by VTTAssets** [comment]
Yes, and I am at a total loss how to load the PNG within the CSS dynamically...

**Comment by VTTAssets** [comment]
Ha! base64 encoded images to the rescue! Fixed
