### ISSUE TITLE
Scenes are importing WEBP even if ORIG is selected

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#224]
**Reported by:** cojo on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/684421955314909194/724707536401334292)
  

  
> hi, <@!144089283685384193> I think there is a bug with the scene import - I am trying to get the png/jpg files like so :
  
**Attachments:** [unknown.png](https://cdn.discordapp.com/attachments/684421955314909194/724707535994748968/unknown.png)
  
compares number with string, resulting in false -> WEBP

**Comment by cojoMan** [comment]
aditional steps - I enabled/disabled the module, checked for updates, and restarted FVTT

**Comment by VTTAssets** [comment]
Fixed

**Comment by VTTAssets** [comment]
just fyi: Fixed = in next update ;)
