### ISSUE TITLE
Module ignores scene image format setting

### ISSUE THREAD

**Issue by ohanar** [VTTAssets/vtta-dndbeyond#227]
If the scene image format is set to use the original image format, the module still uses webp. I tracked this down, to the fact that you do a strict equality [here](https://github.com/VTTAssets/vtta-dndbeyond/blob/master/src/messaging/type/add/page.js#L298), even though the setting is a string and the constant is a number.

**Comment by VTTAssets** [comment]
Duplicate of #224
