### ISSUE TITLE
Failed Monster Parsing: Any Dragon

### ISSUE THREAD

**Issue by Jyro117** [VTTAssets/vtta-dndbeyond#229]
Got a parsing error while attempting to import any dragon, examples:

https://www.dndbeyond.com/monsters/red-dragon-wyrmling
https://www.dndbeyond.com/monsters/young-green-dragon
https://www.dndbeyond.com/monsters/adult-blue-dragon
https://www.dndbeyond.com/monsters/ancient-gold-dragon

**Comment by VTTAssets** [comment]
This is already fixed in the 3.1.4, can you confirm that on your end?

**Comment by Jyro117** [comment]
Confirmed looks fixed on my end (chrome extension 3.1.4 and module 3.1.2)
