### ISSUE TITLE
Issue Importing Mind Flayer

### ISSUE THREAD

**Issue by marcabomb** [VTTAssets/vtta-dndbeyond#267]
Having issue importing Mind Flayer from DND Beyond over to Foundry. Going through chrome console looks like some content is grabbed but then errors out. The import button is also missing from the page.

jquery error:
jquery-3.4.1-slim.min.js:2 Uncaught TypeError: Cannot read property 'preparation' of undefined

Partial console output:
dndbeyond_monster.js:2907 Damage to crits :  2d10 + 4 ["2d10"]
dndbeyond_monster.js:2907 Damage to crits :  10d10 ["10d10"]
dndbeyond_monster.js:2907 Damage to crits :  4d8 + 4 ["4d8"]
monsters.js:1 {head: {…}, body: null}
monsters.js:1 Items
monsters.js:1 (5) [{…}, {…}, {…}, {…}, {…}]
monsters.js:1 ##################################################
monsters.js:1 VTTA D&DBeyond: Monster (Basic Parsing) done:
monsters.js:1 {name: "Mind Flayer", type: "npc", items: Array(5), flags: {…}, data: {…}}data: abilities: cha: {value: 17, mod: 3, save: 0}con: {value: 12, mod: 1, save: 0}dex: {value: 12, mod: 1, save: 0}int: {value: 19, mod: 4, save: 7, proficient: 1}str: {value: 11, mod: 0, save: 0}wis: {value: 17, mod: 3, save: 0}__proto__: Objectattributes: ac: {min: 10, value: 15}hp: {min: 0, max: 71, value: 71, temp: 0, tempmax: 0, …}init: {value: 0, bonus: 0, mod: 1, prof: 0, total: 0}prof: 3speed: {value: 30, special: ""}spellLevel: 0spellcasting: "int"spelldc: 10__proto__: Objectcurrency: cp: 0ep: 0gp: 0pp: 0sp: 0__proto__: Objectdetails: alignment: "lawful evil"biography: {value: "<p>Mind flayers, also called illithids, are the sc…r transforming it into an intellect devourer.</p>", public: "<p>Mind flayers, also called illithids, are the sc…r transforming it into an intellect devourer.</p>"}cr: 7environment: "underdark"race: ""source: "Monster Manual, pg. 222"type: "aberration"xp: {xp: {…}}__proto__: Objectresources: lair: {value: false, initiative: 0}legact: {value: 0, max: 0}legres: {value: 0, max: 0}__proto__: Objectskills: acr: {value: 0, ability: "dex", bonus: 0, mod: 1, passive: 11}ani: {value: 0, ability: "wis", bonus: 0, mod: 3, passive: 13}arc: {value: 1, ability: "int", bonus: 0, mod: 7, passive: 17}ath: {value: 0, ability: "str", bonus: 0, mod: 0, passive: 10}dec: {value: 1, ability: "cha", bonus: 0, mod: 6, passive: 16}his: {value: 0, ability: "int", bonus: 0, mod: 4, passive: 14}ins: {value: 1, ability: "wis", bonus: 0, mod: 6, passive: 16}inv: {value: 0, ability: "int", bonus: 0, mod: 4, passive: 14}itm: {value: 0, ability: "cha", bonus: 0, mod: 3, passive: 13}med: {value: 0, ability: "wis", bonus: 0, mod: 3, passive: 13}nat: {value: 0, ability: "int", bonus: 0, mod: 4, passive: 14}per: {value: 1, ability: "cha", bonus: 0, mod: 6, passive: 16}prc: {value: 1, ability: "wis", bonus: 0, mod: 6, passive: 16}prf: {value: 0, ability: "cha", bonus: 0, mod: 3, passive: 13}rel: {value: 0, ability: "int", bonus: 0, mod: 4, passive: 14}slt: {value: 0, ability: "dex", bonus: 0, mod: 1, passive: 11}ste: {value: 1, ability: "dex", bonus: 0, mod: 4, passive: 14}sur: {value: 0, ability: "wis", bonus: 0, mod: 3, passive: 13}__proto__: Objectspells: spell0: {value: 0, max: 0}spell1: {value: 0, max: 0}spell2: {value: 0, max: 0}spell3: {value: 0, max: 0}spell4: {value: 0, max: 0}spell5: {value: 0, max: 0}spell6: {value: 0, max: 0}spell7: {value: 0, max: 0}spell8: {value: 0, max: 0}spell9: {value: 0, max: 0}__proto__: Objecttraits: ci: {value: Array(0), custom: ""}di: {value: Array(0), custom: ""}dr: {value: Array(0), custom: ""}dv: {value: Array(0), custom: ""}languages: {value: Array(2), custom: "Telepathy 120 ft."}senses: "Darkvision 120 ft."size: "med"__proto__: Object__proto__: Objectflags: {vtta: {…}}items: (5) [{…}, {…}, {…}, {…}, {…}]name: "Mind Flayer"type: "npc"__proto__: Object
monsters.js:1 ##################################################
dndbeyond_monster.js:3876 Beyond20: D&D Beyond Monster module loaded.
monsters.js:1 Found spell from query:
monsters.js:1 null
monsters.js:1 Found spell from query:
monsters.js:1 {_id: "sX5HY232rBirSk1k", name: "Levitate"}name: "Levitate"_id: "sX5HY232rBirSk1k"__proto__: Object
jquery-3.4.1-slim.min.js:2 jQuery.Deferred exception: Cannot read property 'preparation' of undefined TypeError: Cannot read property 'preparation' of undefined
    at HTMLAnchorElement.<anonymous> (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/dndbeyond/monsters.js:1:56338)
    at Function.each (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/libs/jquery-3.4.1-slim.min.js:2:2981)
    at E.fn.init.each (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/libs/jquery-3.4.1-slim.min.js:2:1623)
    at HTMLDocument.<anonymous> (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/dndbeyond/monsters.js:1:55928)
    at Generator.next (<anonymous>)
    at m (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/dndbeyond/monsters.js:1:51410)
    at r (chrome-extension://mhbmahbbdgmmhbbfjbojneimkbkamoji/dndbeyond/monsters.js:1:51613) undefined
E.Deferred.exceptionHook @ jquery-3.4.1-slim.min.js:2
t @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
Promise.then (async)
e @ jquery-3.4.1-slim.min.js:2
t @ jquery-3.4.1-slim.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
fire @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
ready @ jquery-3.4.1-slim.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
jquery-3.4.1-slim.min.js:2 Uncaught TypeError: Cannot read property 'preparation' of undefined
    at HTMLAnchorElement.<anonymous> (monsters.js:1)
    at Function.each (jquery-3.4.1-slim.min.js:2)
    at E.fn.init.each (jquery-3.4.1-slim.min.js:2)
    at HTMLDocument.<anonymous> (monsters.js:1)
    at Generator.next (<anonymous>)
    at m (monsters.js:1)
    at r (monsters.js:1)
(anonymous) @ monsters.js:1
each @ jquery-3.4.1-slim.min.js:2
each @ jquery-3.4.1-slim.min.js:2
(anonymous) @ monsters.js:1
m @ monsters.js:1
r @ monsters.js:1
setTimeout (async)
E.readyException @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
e @ jquery-3.4.1-slim.min.js:2
t @ jquery-3.4.1-slim.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
fire @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
t @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
Promise.then (async)
e @ jquery-3.4.1-slim.min.js:2
t @ jquery-3.4.1-slim.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
fire @ jquery-3.4.1-slim.min.js:2
c @ jquery-3.4.1-slim.min.js:2
fireWith @ jquery-3.4.1-slim.min.js:2
ready @ jquery-3.4.1-slim.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2
(anonymous) @ jquery-3.4.1-slim.min.js:2

**Comment by VTTAssets** [comment]
It seems to be related to the spell lookup from Foundry (Spell: Levitate) which you probably mouse-overed to get the details from. I just fixed a small error there and will push the fix, so can you please

- update the module to 3.1.9 (I guess, latest version)
- Chrome extension is recent (3.1.5)

Please report back here, thanks!

**Comment by VTTAssets** [comment]
(I could import the Monster without issues right now)

**Comment by marcabomb** [comment]
I updated to latest module version and the import is working for me now. Thank you!
