### ISSUE TITLE
Domain spells are no longer imported with character import

### ISSUE THREAD

**Issue by venom986** [VTTAssets/vtta-dndbeyond#278]
This changed recently, almost certainly as a result of changes on the dndbeyond side on August 17, 2020 as part of their updates to support extended spell lists and class variants.

Whereas before, domain spells existed on the character in the JSON response from the v3 character-service, they no longer do.

**Comment by venom986** [comment]
My assumption is that in the dndbeyond backend the domain spells (and maybe similar types of spells granted by racial or class features) are now part of the sub-class feature as opposed to part of the character's spell list.

As there is no reference whatsoever to these spells in the JSON response anymore, it may be necessary to somehow represent extended spell lists on the features themselves in Foundry if possible?

**Comment by venom986** [comment]
Or DDB may just need to account for the backend change within the character-service still.

**Comment by VTTAssets** [comment]
Resolved in using the character import feature (finger's crossed), see PR #283
