### ISSUE TITLE
emdash can corrupt roll formulas for certain sheets.

### ISSUE THREAD

**Issue by MajorVictory** [VTTAssets/vtta-dndbeyond#280]
When importing a monster, if the roll formula contains an emdash (—) character instead of a standard dash (-), it can corrupt the roll formula when loading into certain sheets.

Suggest to convert all emdash characters in formulas into standard dashes to avoid this issue.

**Comment by VTTAssets** [comment]
Can you give me an example monster where that happens? I do build all formulas by hand, so I would love to see the data myself.

**Comment by MajorVictory** [comment]
The Spectator monster from DnDBeyond has one in the Bite attack '(1d6 − 1)'

https://www.dndbeyond.com/monsters/spectator

**Comment by VTTAssets** [comment]
This is fixed in 3.0.9 (upcoming release), thanks for the report!
