### ISSUE TITLE
Request: Omit "Ft" when importing walking speed

### ISSUE THREAD

**Issue by geirsagberg** [VTTAssets/vtta-dndbeyond#291]
Hi, thanks for the great work on this module!

I am using Token Mold for its overlay functions, letting me show HP, speed and AC:
![image](https://user-images.githubusercontent.com/594564/93387344-5b957f00-f869-11ea-995f-78975432c78a.png)

For monsters this works fine.

However, for players, speed gets the "ft" suffix:
![image](https://user-images.githubusercontent.com/594564/93387391-736d0300-f869-11ea-85dd-7cea42fd6a8d.png)

As far as I can tell, this suffix is not present in the JSON from dndbeyond and must therefore be added by the import process. Would therefore be nice to have an option to disable this suffix being added, both to better match imported monsters, as well as more concise view in overlays.

**Comment by VTTAssets** [comment]
I am doing it the way Foundry does it and afaik the ft suffix is present there. I understand that it might look nicer to you, but I will not overburden the tool with options for all bells and whistles, as this contradicts the "ease of use" approach I am trying to follow while developing. Sorry!
