### ISSUE TITLE
Getting a gateway timeout trying to download the module

### ISSUE THREAD

**Issue by ericloyd** [VTTAssets/vtta-dndbeyond#309]
Getting a "504 Gateway Time-out" when trying to donwload the asset file from https://get.vttassets.com/modules/vtta-dndbeyond/stable

**Comment by Zulkano** [comment]
I'm having this same issue about two days ago. I can confirm that it's failed installation from the following three scenarios:

- Installing from FoundryVTT, install module section
- Installing from FoundryVTT, install module section, copy and pasting json link
- Trying to download directly from vttassets site above

I can also confirm that it was working prior to two days ago.

**Comment by RobinKuiper** [comment]
Same thing for me indeed, is there any other way to get it for now? I really wanted to test this before our first session with Foundry.

**Comment by ericloyd** [comment]
Her was my partial solution.

1. I downloaded the master zip file from this github repository.
2. I put it in the foundrydata directory (I'm running Linux) into Data/modules
3. I unzipped it and renamed the resulting vtta-dndbeyond-master directory to vtta-dndbeyond
4. At this point, you normally would be able to restart your game server and load the module, but there is a typo/mistake in the module.json file:
5. Change "https://www.vttassets.com/**asset**/vtta-dndbeyond" to "https://www.vttassets.com/**assets**/vtta-dndbeyond"
6. Now restart game server and you can load the module

Note that this claims to be out of date and that an update is available.  Until the gateway timeout is fixed, that will fail to upload.

The module *mostly* worked for me.  I got two characters to upload but a third failed, and I gave up and went to bed.

**Comment by ericloyd** [comment]
My instructions may no longer be valid, as I see @akrigline has updated the json file.  I'll play with it and see if it works now.

**Comment by ericloyd** [comment]
Looks like the new module.json does fix the problem, but the download/install links on the main page at https://www.vttassets.com/assets/vtta-dndbeyond appear to still be broken.

So my suggestion of downloading the zip file manually and installing it are valid, but you no longer need to make changes to module.zip and the check for updates works.

Thanks, @akrigline!

**Comment by akrigline** [comment]
This module is very much on life support right now. The infrastructure behind it's accompanying proxy server and chrome extension are not public and if they go down that is gg.

Honestly if recommend switching to MrPrimate's ddb-importer. It does not handle adventure imports though.

**Comment by ericloyd** [comment]
Thanks.  Will investigate.

**Comment by MrPrimate** [comment]
This should now work
