### ISSUE TITLE
Color Spray has spec. reqs for dice

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#34]
**Reported by:** Penfold on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/625267799928995840/695377389055639607)
  

  
> Just done some testing with VTTA Beyond & Minor QoL Improvements, trying to figure out how to make a couple of spells do the right thing: given Color Spray's dice roll is not damage but number of HD affected, I'm guessing it's just one of those where the player shouldn't hit the 'Damage' button 😄
  
Applies to damage instead of #target

**Comment by fleetfootmike** [comment]
"Roll 6d10; the total is how many hit points of creatures this spell can effect. Creatures in a 15-foot cone originating from you are affected in ascending order of their current hit points (ignoring unconscious creatures and creatures that can’t see).

Starting with the creature that has the lowest current hit points, each creature affected by this spell is blinded until the spell ends. Subtract each creature’s hit points from the total before moving on to the creature with the next lowest hit points."
