### ISSUE TITLE
Pressing enter in character sheet opens the D&D Beyond Importer window

### ISSUE THREAD

**Issue by mtvjr** [VTTAssets/vtta-dndbeyond#4]
Foundry Version: Beta 0.4.7
D&D Beyond Importer Version: 2.0
5e Module Version: 0.82
Browsers Affected: Chrome, Firefox
Permissions Affected: GM, Player

## Issue Overview

When a character actor's character sheet is open and a text-edit field is focused, pressing the <enter> key will open the D&D Beyond Importer window for the character.

## Desired Result

The D&D Beyond Importer window is not opened and the text-edit field is unfocused.

**Comment by VTTAssets** [comment]
Added `type="button"`to the [B] button to avoid being triggered on form submit
