### ISSUE TITLE
Wondrous items not parsing charges

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#5]
**Reported by:** Jacket on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/684500792433967105/685143659611553847)
  

  
> https://www.dndbeyond.com/magic-items/ring-of-evasion
  
**Attachments:** [ring-of-evasion.json](https://cdn.discordapp.com/attachments/684500792433967105/685143659707891725/ring-of-evasion.json)
  
Forgive me if this has already been brought up or asked about, but when parsing character items other it looks like equipped magic items don't retain their charge information and instead become loot:
https://cdn.discordapp.com/attachments/625267799928995840/684814324539326497/beyond.PNG
https://cdn.discordapp.com/attachments/625267799928995840/684814417703206920/unknown.png
This should be the relevant JSON I think:
```
limitedUse": {
                    "maxUses": 3,
                    "numberUsed": 0,
                    "resetType": "Dawn",
                    "resetTypeDescription": "Regains 1d3 expended charges daily at dawn"
}```

**Comment by VTTAssets** [comment]
Staves have the `getUses(...)`, line 118:
```
let getUses = data => {
  // uses: { value: 0, max: 0, per: null }
  if (data.limitedUse) {
    if (data.limitedUse.resetType === "Consumable") {
      return {
        max: data.limitedUse.maxUses,
        value: data.limitedUse.numberUsed
          ? data.limitedUse.maxUses - data.limitedUse.numberUsed
          : data.limitedUse.maxUses,
        per: "charges"
      };
    } else {
      return {
        max: data.limitedUse.maxUses,
        value: data.limitedUse.numberUsed
          ? data.limitedUse.maxUses - data.limitedUse.numberUsed
          : data.limitedUse.maxUses,
        per: "charges"
      };
    }
  } else {
    // default
    return { value: 0, max: 0, per: null };
  }
};
```

which could be added (per default?) to other item types, too. Perhaps only to rings?

**Comment by VTTAssets** [comment]
Ring of Evasion:
https://discordapp.com/channels/613704572782903312/684500792433967105/685143659611553847

Ingot of  the Skol: https://discordapp.com/channels/613704572782903312/684500792433967105/685147962875445288

**Comment by JacketsMask** [comment]
Here's the D&DB links if you need to reference them at all:
https://www.dndbeyond.com/magic-items/ring-of-evasion
https://www.dndbeyond.com/magic-items/ingot-of-the-skold-rune
