### ISSUE TITLE
Spells imported from character sheet do not have "spell preparation mode" selection

### ISSUE THREAD

**Issue by Brunhine** [VTTAssets/vtta-dndbeyond#56]
Spells imported from character sheet do not have "spell preparation mode" selection.

This results in spells not counting towards count of spells prepared, and thusly does not consume a spell slot when cast

potentially related to #46

**Comment by MrPrimate** [comment]
This should be fixed by https://github.com/VTTAssets/vtta-dndbeyond/pull/38 which is in the next release
