### ISSUE TITLE
spell.preparationModes does not include Fighter class

### ISSUE THREAD

**Issue by JimKuhn** [VTTAssets/vtta-dndbeyond#67]
I am trying to import a character that is an Eldritch Knight (and now has access to Wizard spells).  On import, the class lookup fails in getSpellPreparationMode (spells.js) as **Fighter** isn't one of the options.  classPrepMode is then undefined.

```javascript
    if (prepMode) {
      prepMode = classPrepMode.value;
    };
```

For completeness, the spell happens to be Dancing Lights but I imagine that is irrelevant.

EDIT: And, as soon as I submitted this, I see there is an open pull request with this change (#62)

**Comment by MrPrimate** [comment]
Fixed!
