### ISSUE TITLE
Resolve template strings for certain spells/items

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#76]
**Reported by:** Diabolicbutterfly on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/613704573223174154/702443665787977800)
  

  
> Whenever you finish a long rest, you can touch up to {{scalevalue}} nonmagical objects, imbuing each of them with one of your artificer infusions, turning it into a magic item. You can attune yourself to the item the instant you infuse it, or you can forgo attunement so that someone else can attune to the item. Your infusion remains in an item indefinitely, but when you die, the infusion vanishes after {{modifier:int@min:1#unsigned}} days. The infusion also vanishes if you give up your knowledge of the infusion or you exceed your maximum number of infusions.
  
Examples: Artificer infusions, Spell: Healing Hands

**Comment by MrPrimate** [comment]
Paladin Lay on Hands

**Comment by VTTAssets** [comment]
Fighter, Second Wind HP regen

**Comment by MrPrimate** [comment]
- Fighter, action surge
- Sneak Attack

**Comment by mtvjr** [comment]
Paladin Divine Sense

**Comment by MrPrimate** [comment]
Fixed in #197
