### ISSUE TITLE
Spell DC appears correctly only after Refresh

### ISSUE THREAD

**Issue by VTTAssets** [VTTAssets/vtta-dndbeyond#87]
**Reported by:** ohporter on **Source:** [VTTAssets Discord](https://discordapp.com/channels/613704572782903312/684421955314909194/704787481622478897)
  

  
> I'm seeing spell DCs reflecting the wrong value on a fresh import of a character from DDB. An F5 refresh works around it...seems like the code to calculate the DCs is not getting triggered after import.

**Comment by bashfulben** [comment]
Just to throw in, neither refreshing nor reuploading seems to correct this. Have to manually update the saving throw calculation to include the spell modifier for all characters.

**Comment by MrPrimate** [comment]
Hmm, reloading the page has always fixed this for me. Do you have a character json you can share?

**Comment by bashfulben** [comment]
Sorry only seeing this yes I’ve attached the Json I noticed this on below:

https://www.dndbeyond.com/profile/jmoriar/characters/9950046/json

**Comment by VTTAssets** [comment]
So I know it has been super long time since you posted that - I am cleaning up some of the issues right now, checking what's working and what's still up. I am importing said character and the vicious mockery has a DC15 when cast, which is 8 + 3 (prof) + 4 (cha mod), so it seems correct. Can you confirm that?

**Comment by VTTAssets** [comment]
Closing due to no response
