### ISSUE TITLE
Character Import should have an import policy similar to compendium import

### ISSUE THREAD

**Issue by shawndibble** [VTTAssets/vtta-dndbeyond#90]
When doing a character import from DnDBeyond, all information is reset and overwritten. If I make any changes to a weapon or spell, those settings are lost. This can be annoying when I want to add icons or setup custom settings (ie: offhand dagger attack with no modifiers).

Suggestion: Have an import option similar to the compendium import policy that the user can pick when they do their import.

Filters should impact the inventory, features and spellbook section.
Default should be: Save new entries only, do not override existing records.

User should be able to pick a different setting for if they want to override all settings, or if they already have some settings in place, can have it so that only new entries are added.

**Comment by VTTAssets** [comment]
I am ready to toss ideas around, but given your example for one specific item ("offhand dagger") that could be special I have no great idea how to implement that as an option without putting out a myriad of different options. 

The import policies are referring to the compendiums only, but not on items on a character sheet, that's mainly the issue. I can see that we could use a different approach here, but I am - as I said - no "zündende Idee" on how to do that without a cumbersome UI. 

Let's talk about that dagger for a moment:When we had an option for "do not update existing items" which would preserve any local changes, and the daggers damage would be different, but not it's name - it would not carry over (comparision is always on the name level and not for every single attribute within an item). 

I can see that we would cover much ground with such an option, but it's not ideal though.

**Comment by shawndibble** [comment]
That was just an example. But it would more so only add new entries from DnDBeyond. New inventory, spells, traits, etc... But not override any existing entries it finds. I would assume it would do some kind of diff check and add what is new based on the name. 

I say this because, my life cleric isn't getting his Preserve Life applied to his healing abilities. Or the warlock not getting Agonizing Blast being applied to his Eldritch Blast. They can change the skill by adjusting the calculation themselves, but another import will override those changes. Same if the player decides to add icons. All that gets overwritten when the player syncs with dndbeyond.

Honestly, it would be nice if all those features that impacted spells/abilities/attacks were done in foundry but I don't see that happening any time soon with the current import.

However, being able to use dndbeyond to assist with the leveling up is great in that the player can add the new skills/spells/traits/features with no problem. These new things are what I would like to see getting imported only.

A later options would be to have a diff screen showing the player any changes from an existing entry on his/her sheet and what is coming from dndbeyond so that they can figure if they want to correct those changes, but that feels cumbersome to me.

**Comment by MrPrimate** [comment]
FYI your Warlock should get Agonising Blast when imported now :)

**Comment by MrPrimate** [comment]
The next release will bring these features

**Comment by venom986** [comment]
For some reason, despite the fact that the issue is closed, the task card on the project still has a status of Under Consideration.
